name: glow
description: "Flutter app showcasing Breez SDK - Nodeless (Spark Implementation)."
publish_to: 'none'
version: 0.1.0+11

environment:
  sdk: ^3.9.2

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  
  # Breez SDK
  breez_sdk_spark_flutter:
    git:
      url: https://github.com/breez/breez-sdk-spark-flutter
  
  # State Management
  flutter_riverpod: ^3.0.3
  
  # Wallet & Cryptography
  bip39: ^1.0.6
  crypto: ^3.0.7
  flutter_secure_storage: ^9.2.4
  
  # Storage & Data
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  
  # UI Components
  auto_size_text: ^3.0.0
  flutter_svg: ^2.2.3  # TODO: Replace with icon_bundler or similar
  pretty_qr_code: ^3.5.0
  shimmer: ^3.0.0
  
  # Image & Camera
  flutter_cache_manager: ^3.4.1
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.3
  
  # Utilities
  archive: ^4.0.7
  collection: ^1.19.1
  device_info_plus: ^12.3.0
  equatable: ^2.0.7
  intl: ^0.20.2
  logger: ^2.6.2
  path: ^1.9.1
  share_plus: ^12.0.1
  timeago: ^3.7.1
  typeaheadx: ^0.0.2
  local_auth: ^3.0.0
  local_auth_android: ^2.0.3
  local_auth_darwin: ^2.0.1
  lottie: ^3.3.2

dependency_overrides:
  # Breez SDK
  breez_sdk_spark_flutter:
    path: ../spark-sdk/packages/flutter

dev_dependencies:
  # Linting
  flutter_lints: ^6.0.0
  
  # Testing
  build_runner: ^2.10.4
  integration_test:
    sdk: flutter
  mockito: ^5.6.1
  path_provider_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/animations/lottie/
    - assets/icon/
    - assets/image/
    - assets/svg/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
