name: glow
description: "Flutter app showcasing Breez SDK - Nodeless (Spark Implementation)."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter  
  breez_sdk_spark_flutter:
    git:
      url: https://github.com/breez/breez-sdk-spark-flutter
  flutter_riverpod: ^3.0.3
  path_provider: ^2.1.5
  pretty_qr_code: ^3.5.0

  device_info_plus: ^12.2.0
  logger: ^2.6.2
  archive: ^4.0.7
  share_plus: ^12.0.1

  bip39: ^1.0.6
  flutter_secure_storage: ^10.0.0-beta.4
  crypto: ^3.0.6  # For wallet ID generation

  shared_preferences: ^2.5.3
  auto_size_text: ^3.0.0

  flutter_svg: ^2.2.1 ## To be replaced with a more performant alternative, such as icon_bundler etc.

  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  flutter_cache_manager: ^3.4.1
  mobile_scanner: ^7.1.3
  equatable: ^2.0.7
  shimmer: ^3.0.0
  intl: ^0.20.2
  timeago: ^3.7.1
  path: ^1.9.1
  
dependency_overrides:
  breez_sdk_spark_flutter:
    path: ../spark-sdk/packages/flutter

dev_dependencies:
  flutter_lints: ^6.0.0

  mockito: ^5.4.0
  build_runner: ^2.4.0  # For generating mocks
  path_provider_platform_interface: ^2.1.2

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icon/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
